databases:
  - name: bayan-db
    plan: free
    databaseName: bayan
    user: bayan

services:
  - type: web
    name: bayan-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run seed && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bayan-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PUBLIC_APP_URL
        value: https://bayan-frontend.onrender.com

  - type: web
    name: bayan-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://bayan-backend-wpbu.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
